name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'docs'
  - title: 'Dependencies updates'
    labels:
      - 'deps'

exclude-labels:
 - 'skip'

autolabeler:
  - label: 'bug'
    title:
      - '/.*(\[fix\]|fix\(.*\)).*/'
      - '/.*(\[ci\]|ci\(.*\)).*/'
  - label: 'deps'
    title:
      - '/.*chore\(deps\).*/'
  - label: 'patch'
    title:
      - '/.*(\[fix\]|fix\(.*\):).*/'
  - label: 'enhancement'
    title:
      - '/.*(\[feat\]|feat\(.*\)).*/'
  - label: 'minor'
    title:
      - '/.*(\[feat\]|feat\(.*\)).*/'
  - label: 'skip'
    title:
      - '/.*\[skip\].*/'
      - '/.*(\[docs\]|docs\(.*\):).*/'
  - label: 'major'
    title:
      - '/.*(\[breaking\]|breaking:).*/'

replacers:
  - search: '/\[feat\]/g'
    replace: ''
  - search: '/\[fix\]/g'
    replace: ''
  - search: '/\[skip\]/g'
    replace: ''
  - search: '/\[breaking\]/g'
    replace: ''

template: |
  # What's Changed

  $CHANGES
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.