/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: compute-capsule@amazon.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Error {
    /// A description of the error condition
    #[serde(rename = "fault_message", skip_serializing_if = "Option::is_none")]
    pub fault_message: Option<String>,
}

impl Error {
    pub fn new() -> Error {
        Error {
            fault_message: None,
        }
    }
}
