/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: compute-capsule@amazon.com
 * Generated by: https://openapi-generator.tech
 */

/// BalloonStatsUpdate : Update the statistics polling interval, with the first statistics update scheduled immediately. Statistics cannot be turned on/off after boot.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BalloonStatsUpdate {
    /// Interval in seconds between refreshing statistics.
    #[serde(rename = "stats_polling_interval_s")]
    pub stats_polling_interval_s: i32,
}

impl BalloonStatsUpdate {
    /// Update the statistics polling interval, with the first statistics update scheduled immediately. Statistics cannot be turned on/off after boot.
    pub fn new(stats_polling_interval_s: i32) -> BalloonStatsUpdate {
        BalloonStatsUpdate {
            stats_polling_interval_s,
        }
    }
}
