/*
 * Firecracker API
 *
 * RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: compute-capsule@amazon.com
 * Generated by: https://openapi-generator.tech
 */

/// CpuTemplate : The CPU Template defines a set of flags to be disabled from the microvm so that the features exposed to the guest are the same as in the selected instance type. Works only on Intel.

/// The CPU Template defines a set of flags to be disabled from the microvm so that the features exposed to the guest are the same as in the selected instance type. Works only on Intel.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CpuTemplate {
    #[serde(rename = "C3")]
    C3,
    #[serde(rename = "T2")]
    T2,
    #[serde(rename = "T2S")]
    T2S,
    #[serde(rename = "T2CL")]
    T2Cl,
    #[serde(rename = "T2A")]
    T2A,
    #[serde(rename = "None")]
    None,
}

impl ToString for CpuTemplate {
    fn to_string(&self) -> String {
        match self {
            Self::C3 => String::from("C3"),
            Self::T2 => String::from("T2"),
            Self::T2S => String::from("T2S"),
            Self::T2Cl => String::from("T2CL"),
            Self::T2A => String::from("T2A"),
            Self::None => String::from("None"),
        }
    }
}

impl Default for CpuTemplate {
    fn default() -> CpuTemplate {
        Self::C3
    }
}
